Neos:
  Neos:
    Ui:
      resources:
        javascript:
          '@carbon/videoplatformeditor':
            resource: 'resource://Carbon.VideoPlatformEditor/Public/JavaScript/Plugin.js'
        stylesheets:
          '@carbon/videoplatformeditor':
            resource: 'resource://Carbon.VideoPlatformEditor/Public/JavaScript/Plugin.css'

    userInterface:
      inspector:
        dataTypes:
          Carbon\VideoPlatformEditor\Video:
            editor: Carbon.VideoPlatformEditor/Inspector/Editors/VideoPlatformEditor
